variables:
  Agent.Source.Git.ShallowFetchDepth: 5

trigger:
- norm_opt

jobs:

# This job build the wheels
- job: Build
  pool:
    vmImage: 'vs2017-win2016'

  steps:

  - powershell: |
      (New-Object System.Net.WebClient).DownloadFile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe",".\Miniconda3.exe")
    displayName: Download Miniconda

  - script: start /wait "" Miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=$(Agent.BuildDirectory)\CONDA
    displayName: Install Miniconda

  - script: |
      call $(Agent.BuildDirectory)\CONDA\Scripts\activate
      conda env create -f environment_win.yml
    displayName: Create Conda environment
  - script: |
      call $(Agent.BuildDirectory)\CONDA\Scripts\activate simnibs_env
      python setup.py bdist_wheel
      pip install jinja2 conda-pack
      python packing\pack.py dist\
      copy dist\* $(Build.ArtifactStagingDirectory)
      copy environment_win.yml $(Build.ArtifactStagingDirectory)
      cp simnibs_installer_windows.exe  $(Build.ArtifactStagingDirectory)
    displayName: Build SimNIBS
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: windows
    displayName: Publish Artifact

# Now we test the previously build wheels on different windows versions

- job: Test
  dependsOn: Build
  strategy:
    matrix:
      Windows-2016:
        vmImage: 'vs2017-win2016'
      Windows-2019:
         vmImage: 'windows-2019'

  pool:
    vmImage: $(vmImage)
    maxParallel: 4

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'windows'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download Wheel

  - script: |
      start /wait "" $(System.ArtifactsDirectory)\windows\simnibs_installer_windows.exe /S /D=%cd%\simnibs_install
      simnibs_install\bin\simnibs_python -m pytest simnibs_install\simnibs_env\lib\site-packages\simnibs\tests --junit-xml=test-results.xml
    displayName: Install SimNIBS and run unit tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Publish test results'

# Finally, if everything went fine, we upload to GitHub releases as a draft

- job: Release
  dependsOn: Test
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'windows'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download Wheel

  - task: GithubRelease@0
    displayName: Edit GitHub Release
    inputs: 
      gitHubConnection: guilhermebs # I use my connection because github does not generate OAuth token for organizations
      repositoryName: simnibs/simnibs
      action: edit
      tag: dev
      assets: $(System.ArtifactsDirectory)\windows\*
      assetUploadMode: 'replace'
      isDraft: true


