trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'macOS-latest'
    maxParallel: 4

  steps:
  # Install certificates for signing the package
  - checkout: 'self'
    fetchDepth: '0'
    fetchTags: 'true'
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'certificate_installer_new.p12'
      certPwd: '$(P12password)'
      keychain: 'temp'
    displayName: Install Installer Certificate
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'certificate_application_new.p12'
      certPwd: '$(P12password)'
      keychain: 'temp'
    displayName: Install Application Certificate
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH
  - bash: |
      conda env create -f environment_macOS.yml
    displayName: Create Conda environment
  - bash: |
      source activate simnibs_env
      export MACOSX_DEPLOYMENT_TARGET=10.9
      python -m pip wheel . -w ./dist --no-deps --use-feature=in-tree-build
      pip install jinja2 conda-pack setuptools-scm
      python packing/pack.py dist --developer-id 8J5V4KS7H4
      cp dist/* $(Build.ArtifactStagingDirectory)
      cp environment_macOS.yml $(Build.ArtifactStagingDirectory)
      cp simnibs_installer_macos.pkg $(Build.ArtifactStagingDirectory)
    displayName: Build SimNIBS
  # https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution
  - bash: |
      xcrun altool --notarize-app -u "$ALTOOL_USER" -p "$ALTOOL_PASSWORD" -f $(Build.ArtifactStagingDirectory)/simnibs_installer_macos.pkg --primary-bundle-id "org.simnibs.pkg"
    env:  
      ALTOOL_PASSWORD: $(altool_password)
      ALTOOL_USER: $(altool_user)
    displayName: Notarize App
#  - bash: |
#      xcrun stapler staple "$(Build.ArtifactStagingDirectory)/simnibs_installer_macos.pkg"
#    displayName: Staple notarization ticket
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: macos
    displayName: Publish Artifact

- job: Test
  dependsOn: Build
  strategy:
    matrix:
      MacOSX-11:
        vmImage: 'macOS-11'
      MacOSX-12:
        vmImage: 'macOS-12'

  pool:
    vmImage: $(vmImage)
    maxParallel: 4

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'macos'
      itemPattern: '**/*.pkg'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download SimNIBS Installer

  - bash: |
      installer -pkg $(System.ArtifactsDirectory)/macos/simnibs_installer_macos.pkg -target CurrentUserHomeDirectory -dumplog
      cat ~/Applications/SimNIBS*/install.log
      ~/Applications/SimNIBS*/bin/simnibs_python -m pytest ~/Applications/SimNIBS*/simnibs_env/lib/python*/site-packages/simnibs --junit-xml=test-results.xml
    displayName: Install SimNIBS and run unit tests
 
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Unit Tests'
      
- job: Examples
  dependsOn: Build
  timeoutInMinutes: 0 # Maximum time (should be 6 hours)
  pool:
    vmImage: 'macOS-latest'
    maxParallel: 4

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'macos'
      itemPattern: '**/*.pkg'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download SimNIBS Installer

  - bash: |
      brew update
      brew install octave
      octave -v
    displayName: Install Octave

  - bash: |
      installer -pkg $(System.ArtifactsDirectory)/macos/simnibs_installer_macos.pkg -target CurrentUserHomeDirectory -dumplog
      cat ~/Applications/SimNIBS*/install.log
      ~/Applications/SimNIBS*/bin/simnibs_python -m pytest ~/Applications/SimNIBS*/simnibs_env/lib/python*/site-packages/simnibs/examples/tests/examples.py -v -s --junit-xml=test-results.xml
    displayName: Install SimNIBS and run tests
 
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Example Tests'

# If everything went fine, we upload the wheel as a draft to GitHub
- job: Release
  dependsOn:
    - Test
    - Examples
#  dependsOn: Build
  
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'macos'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download SimNIBS version
  - bash: |
      xcrun stapler staple "$(System.ArtifactsDirectory)/macos/simnibs_installer_macos.pkg"
    displayName: Staple notarization ticket
  - task: GithubRelease@0
    displayName: Edit GitHub Release
    inputs: 
      gitHubConnection: oulap # I use my connection because github does not generate OAuth token for organizations
      repositoryName: simnibs/simnibs
      action: edit
      tag: dev
      assets: $(System.ArtifactsDirectory)/macos/*
      assetUploadMode: 'replace'
      isDraft: true

