variables:
  Agent.Source.Git.ShallowFetchDepth: 1
  
trigger: none

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y octave
      octave -v
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Install Octave and add conda to PATH

  - bash: |
      conda env create -f environment_linux.yml
    displayName: Create Conda environment

  - bash: |
      source activate simnibs_env
      python setup.py develop
      postinstall_simnibs -d . -s --no-extra-coils 
    displayName: install SimNIBS

  - bash: |
      source activate simnibs_env
      pytest simnibs/examples/tests/examples.py -v -s -x --junit-xml=test-results.xml
    displayName: Run tests
  
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Publish test results'
