variables:
  Agent.Source.Git.ShallowFetchDepth: 1
  
trigger: none

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda env create -f environment_linux.yml
    displayName: Create Conda environment
  - bash: |
      source activate simnibs_env
      python setup.py bdist_wheel
    displayName: Build SimNIBS
  - bash: |
      source activate base
      pip install conda-pack
      python pack.py
      cp simnibs-*.zip $(Build.ArtifactStagingDirectory)
    displayName: Create SimNIBS pack
  - bash: |
      cd pack
      ./install
      $HOME/SimNIBS/bin/simnibs --version
    displayName: Test
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: pack-linux
    displayName: Publish Artifact

- job: MacOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH
  - bash: |
      conda env create -f environment_macOS.yml
    displayName: Create Conda environment
  - bash: |
      source activate simnibs_env
      python setup.py bdist_wheel
    displayName: Build SimNIBS
  - bash: |
      source activate base
      pip install conda-pack
      python pack.py
      cp simnibs-*.zip $(Build.ArtifactStagingDirectory)
    displayName: Create SimNIBS pack
  - bash: |
      cd pack
      ./install
      $HOME/Applications/SimNIBS/bin/simnibs --version
    displayName: Test
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: pack-osx
    displayName: Publish Artifact

- job: Windows
  pool:
    vmImage: 'vs2015-win2012r2'

  steps:
  - powershell: |
      (New-Object System.Net.WebClient).DownloadFile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe",".\Miniconda3.exe")
    displayName: Download Miniconda
  - script: start /wait "" Miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=$(Agent.BuildDirectory)\CONDA
    displayName: Install Miniconda
  - script: |
      call $(Agent.BuildDirectory)\CONDA\Scripts\activate
      conda env create -f environment_win.yml
    displayName: Create Conda environment
  - script: |
      call $(Agent.BuildDirectory)\CONDA\Scripts\activate simnibs_env
      python setup.py bdist_wheel
    displayName: Build SimNIBS
  - script: |
      call $(Agent.BuildDirectory)\CONDA\Scripts\activate base
      pip install conda-pack
      python pack.py
      cp simnibs-*.zip $(Build.ArtifactStagingDirectory)
    displayName: Create SimNIBS pack
  - bash: |
      cd pack
      install
      %LOCALAPPDATA%\SimNIBS\bin\simnibs --version
    displayName: Test
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: pack-windows
    displayName: Publish Artifact

